import { useEffect, useState } from "react";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import DateRangeIcon from "@mui/icons-material/DateRange";
import { Calendar } from "react-calendar";
import moment from "moment";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation } from "swiper";
import "swiper/css";
import "swiper/css/navigation";

export default function Home() {
  const [webinars, setWebinars] = useState([]);
  const [upcomingWebinars, setUpcomingWebinars] = useState([]);
  const [pastWebinars, setPastWebinars] = useState([]);
  const [featuredWebinar, setFeaturedWebinar] = useState({});
  const [openCalendar, setOpenCalendar] = useState(false);

  const handleCalendarBtn = () => {
    setOpenCalendar(!openCalendar);
  };

  useEffect(() => {
    const getWebinars = async () => {
      try {
        const res = await axios.get(
          "https://newraq.raqamyat.com/public/api/webinars"
        );
        if (res.status === 200) {
          setWebinars(await res.data?.data);
          setOpenCalendar(true);
        }
      } catch (error) {
        console.log(error);
      }
    };
    getWebinars();
  }, []);

  useEffect(() => {
    markDays();
    setUpcomingWebinars(
      webinars?.filter((webinar) => {
        return moment(moment(webinar?.date, "DD-MM-YYYY")).isAfter(moment());
      })
    );
    setPastWebinars(
      webinars?.filter((webinar) => {
        return moment(moment(webinar?.date, "DD-MM-YYYY")).isBefore(moment());
      })
    );
    if (upcomingWebinars?.length > 0) {
      setFeaturedWebinar(upcomingWebinars[0]);
    } else if (pastWebinars?.length > 0) {
      setFeaturedWebinar(pastWebinars[pastWebinars?.length - 1]);
    }
  }, [webinars]);

  const markDays = () => {
    const days = document.getElementsByClassName(
      "react-calendar__month-view__days__day"
    );
    for (let b = 0; b < webinars?.length; b++) {
      for (let c = 0; c < days.length; c++) {
        if (
          moment(days[c]?.firstChild.ariaLabel, "MMMM D[,] YYYY").format(
            "DD-MM-YYYY"
          ) === moment(webinars[b]?.date, "DD-MM-YYYY").format("DD-MM-YYYY")
        ) {
          const a = document.createElement("span");
          a.className = "tag";
          if (
            moment(moment(webinars[b]?.date, "DD-MM-YYYY")).isSame(
              moment(),
              "day"
            )
          ) {
            a.style.backgroundColor = "#FF3939";
          } else if (
            moment(moment(webinars[b]?.date, "DD-MM-YYYY")).isAfter(moment())
          ) {
            a.style.backgroundColor = "#00A4F8";
          } else if (
            moment(moment(webinars[b]?.date, "DD-MM-YYYY")).isBefore(moment())
          ) {
            a.style.backgroundColor = "#707070";
          }
          days[c].name = "hasWebinar";
          days[c].appendChild(a);
        }
      }
    }
  };

  return (
    <>
      <Head>
        <title>Raqamyat Webinars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div
          style={{
            visibility: openCalendar ? "visible" : "",
            bottom: openCalendar ? "100px" : "-477px",
            opacity: openCalendar ? 1 : 0,
          }}
          className={styles.calendar}
        >
          <div className={styles.calendarTitle}>
            <div>
              <span style={{ backgroundColor: "#707070" }} />
              <div>Past</div>
            </div>
            <div>
              <span style={{ backgroundColor: "#FF3939" }} />
              <div>Live</div>
            </div>
            <div>
              <span style={{ backgroundColor: "#00A4F8" }} />
              <div>Upcoming</div>
            </div>
          </div>
          <Calendar
            onActiveStartDateChange={markDays}
            calendarType="US"
            formatShortWeekday={(locale, date) => moment(date).format("dd")}
            nextLabel={
              <img className="navIcon" src="/img/next.svg" alt="next" />
            }
            prevLabel={
              <img className="navIcon" src="/img/prev.svg" alt="prev" />
            }
          />
        </div>
        <div className={styles.calendarBtn} onClick={handleCalendarBtn}>
          <div className={styles.left}>
            <DateRangeIcon
              className={styles.calendarIcon}
              htmlColor="#00A4F8"
            />
          </div>

          <div className={styles.right}>Webinars Calendar</div>
        </div>
        <div
          className={styles.backdrop}
          style={{ display: openCalendar ? "block" : "none" }}
          onClick={() => setOpenCalendar(false)}
        ></div>
        <div className={styles.hero}>
          <img className={styles.shapes} src="/img/shapes.svg" alt="shapes" />
          <img className={styles.chart} src="/img/chart.svg" alt="chart" />
          <img className={styles.live} src="/img/live.svg" alt="live" />
          <img className={styles.mic} src="/img/mic.svg" alt="mic" />
          <img className={styles.ccard} src="/img/ccard.svg" alt="ccard" />
          <div className={styles.title}>
            Fintech Knowledge
            <br />
            Unlocked!
          </div>
          <div className={styles.subtitle}>
            Raqamyat Webinars is your Fintech knowledge gate
          </div>
          <button className={styles.registerBtn}>HOW TO REGISTER / JOIN</button>
        </div>
        <div className={styles.parteners}>
          <img src="/img/paymob.png" alt="paymob" />
          <img src="/img/paySky.png" alt="paySky" />
          <img src="/img/fawry.png" alt="fawry" />
          <img src="/img/kashier.png" alt="kashier" />
          <img src="/img/oPay.png" alt="oPay" />
        </div>
        <div className={styles.featuredWebinar}>
          <span className={styles.featuredWebinarBg} />

          <div className={styles.top}>
            <div className={styles.left}>
              <img
                className={styles.webinarImage}
                src={featuredWebinar?.image}
                alt="webinarImage"
              />
              <div className={styles.watchNowBtn}>
                <img
                  className={styles.playIcon}
                  src="/img/play.svg"
                  alt="play"
                />
                Watch Now{" "}
              </div>
            </div>
            <div className={styles.right}>
              <div className={styles.status}>
                {moment(moment(featuredWebinar?.date, "DD-MM-YYYY")).isAfter(
                  moment()
                )
                  ? "Upcoming Webinar"
                  : moment(
                      moment(featuredWebinar?.date, "DD-MM-YYYY")
                    ).isBefore(moment()) && "Last Webinar"}
              </div>
              <div className={styles.dateAndTime}>
                <DateRangeIcon
                  className={styles.icon}
                  fontSize="14px"
                  htmlColor="#707070"
                />
                <div className={styles.date}>
                  {moment(featuredWebinar?.date, "DD-MM-YYYY").format(
                    "dddd[,] MMMM Do YYYY"
                  )}
                </div>
                |
                <div className={styles.time}>
                  {moment(featuredWebinar?.date, "DD-MM-YYYY hh:mm:ss").format(
                    "hh[:]mm A"
                  )}
                </div>
              </div>
              <div className={styles.title}>{featuredWebinar?.name}</div>
              <div className={styles.speaker}>
                <div className={styles.speakerLeft}>
                  <img
                    onError={(e) => (e.target.src = "/img/avatar.png")}
                    src="/img/avatar.png"
                    alt="speaker"
                  />
                </div>
                <div className={styles.speakerRight}>
                  <div className={styles.name}>{featuredWebinar?.speker}</div>
                  <div className={styles.position}>
                    {featuredWebinar?.position}
                  </div>
                  <div className={styles.company}>
                    {featuredWebinar?.company}
                  </div>
                </div>
              </div>
              <div className={styles.register}>
                <button className={styles.btn}>Register Now</button>
              </div>
            </div>
          </div>
          <div className={styles.bottom}>
            <div className={styles.left}>
              <div className={styles.title}>Free Zoom Webinars</div>
              <div className={styles.subtitle}>
                <div>
                  <span>Live Knowledge Sharing Sessions By Industry</span>
                </div>
                <div>
                  <span>Experts On Latest And Trending Skills</span>
                </div>
                <div>
                  <span>And Technologies</span>
                </div>
              </div>
            </div>
            <div className={styles.right}>
              <Link href="/webinars">
                <div>all webinars</div>
                <img src="/img/up-right-arrow.svg" alt="arrow" />
              </Link>
            </div>
          </div>
        </div>
        <div className={styles.upcomingWebinars}>
          <img src="/img/shapes2.svg" className={styles.upcomingWebinarsBg} />
          <div className={styles.header}>Upcoming Webinars</div>
          <Swiper
            slidesPerView={3}
            spaceBetween={150}
            className={styles.swiper}
            modules={[Navigation]}
            navigation={true}
          >
            {Array.isArray(upcomingWebinars) &&
              upcomingWebinars.map((webinar, index) => {
                return (
                  <SwiperSlide key={index} className={styles.slide}>
                    <div className={styles.card}>
                      <div className={styles.dateAndTime}>
                        <DateRangeIcon
                          className={styles.icon}
                          fontSize="14px"
                          htmlColor="#707070"
                        />
                        <div className={styles.date}>
                          {moment(webinar?.date, "DD-MM-YYYY").format(
                            "dddd[,] MMMM Do YYYY"
                          )}
                        </div>
                        |
                        <div className={styles.time}>
                          {moment(webinar?.date, "DD-MM-YYYY hh:mm:ss").format(
                            "hh[:]mm A"
                          )}
                        </div>
                      </div>
                      <div className={styles.title}>{webinar?.name}</div>
                      <div className={styles.speaker}>
                        <div className={styles.speakerLeft}>
                          <img
                            onError={(e) => (e.target.src = "/img/avatar.png")}
                            src={webinar?.author?.image}
                            alt="speaker"
                          />
                        </div>
                        <div className={styles.speakerRight}>
                          <div className={styles.name}>{webinar?.speker}</div>
                          <div className={styles.position}>
                            {webinar?.position}
                          </div>
                          <div className={styles.company}>
                            {webinar?.company}
                          </div>
                        </div>
                      </div>
                      <div className={styles.register}>
                        <button className={styles.btn}>Register Now</button>
                      </div>{" "}
                    </div>
                  </SwiperSlide>
                );
              })}
          </Swiper>
        </div>
        <div className={styles.pastWebinars}>
          <div className={styles.header}>Past Webinars</div>
          <Swiper
            slidesPerView={3}
            spaceBetween={150}
            className={styles.swiper}
            modules={[Navigation]}
            navigation={true}
          >
            {Array.isArray(pastWebinars) &&
              pastWebinars.map((webinar, index) => {
                return (
                  <SwiperSlide key={index} className={styles.slide}>
                    <div className={styles.card}>
                      <div className={styles.dateAndTime}>
                        <DateRangeIcon
                          className={styles.icon}
                          fontSize="14px"
                          htmlColor="#707070"
                        />
                        <div className={styles.date}>
                          {moment(webinar?.date, "DD-MM-YYYY").format(
                            "dddd[,] MMMM Do YYYY"
                          )}
                        </div>
                        |
                        <div className={styles.time}>
                          {moment(webinar?.date, "DD-MM-YYYY hh:mm:ss").format(
                            "hh[:]mm A"
                          )}
                        </div>
                      </div>
                      <div className={styles.title}>{webinar?.name}</div>
                      <div className={styles.speaker}>
                        <div className={styles.speakerLeft}>
                          <img
                            onError={(e) => (e.target.src = "/img/avatar.png")}
                            src="/img/avatar.png"
                            alt="speaker"
                          />
                        </div>
                        <div className={styles.speakerRight}>
                          <div className={styles.name}>{webinar?.speker}</div>
                          <div className={styles.position}>
                            {webinar?.position}
                          </div>
                          <div className={styles.company}>
                            {webinar?.company}
                          </div>
                        </div>
                      </div>
                      <div className={styles.register}>
                        <button className={styles.btn}>Register Now</button>
                      </div>{" "}
                    </div>
                  </SwiperSlide>
                );
              })}
          </Swiper>
        </div>
      </div>
    </>
  );
}
