import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Raqamyat Webinars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.hero}>
          <img className={styles.shapes} src="/img/shapes.svg" alt="shapes" />
          <img className={styles.chart} src="/img/chart.svg" alt="chart" />
          <img className={styles.live} src="/img/live.svg" alt="live" />
          <img className={styles.mic} src="/img/mic.svg" alt="mic" />
          <img className={styles.ccard} src="/img/ccard.svg" alt="ccard" />
          <div className={styles.title}>
            Fintech Knowledge
            <br />
            Unlocked!
          </div>
          <div className={styles.subtitle}>
            Raqamyat Webinars is your Fintech knowledge gate
          </div>
          <button className={styles.registerBtn}>HOW TO REGISTER / JOIN</button>
        </div>
        <div className={styles.parteners}>
          <img src="/img/paymob.png" alt="paymob" />
          <img src="/img/paySky.png" alt="paySky" />
          <img src="/img/fawry.png" alt="fawry" />
          <img src="/img/kashier.png" alt="kashier" />
          <img src="/img/oPay.png" alt="oPay" />
        </div>
        <div className={styles.liveWebinar}>
        <span className={styles.liveWebinarBg} />

          <div className={styles.top}>
          <div className={styles.left}>
            <img src="/img/webinarTest.png" alt="webinarImage" />
          </div>
          <div className={styles.right}></div>

          </div>
          <div className={styles.bottom}>
            <div className={styles.left}>
              <div className={styles.title}>Free Zoom Webinars</div>
              <div className={styles.subtitle}>
                <div>
                  <span>Live Knowledge Sharing Sessions By Industry</span>
                </div>
                <div>
                  <span>Experts On Latest And Trending Skills</span>
                </div>
                <div>
                  <span>And Technologies</span>
                </div>
              </div>
            </div>
            <div className={styles.right}>
              <Link  href="/webinars">
                <div>all webinars</div>
                <img src="/img/up-right-arrow.svg" alt="arrow" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
